[2023-01-05T11:31:52.035+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_pipeline.load_to_postgres manual__2023-01-05T10:53:41.626541+00:00 [queued]>
[2023-01-05T11:31:52.048+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: UK_Accidents_pipeline.load_to_postgres manual__2023-01-05T10:53:41.626541+00:00 [queued]>
[2023-01-05T11:31:52.049+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T11:31:52.050+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-05T11:31:52.070+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T11:31:52.149+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-05 10:53:41.626541+00:00
[2023-01-05T11:31:52.155+0000] {standard_task_runner.py:55} INFO - Started process 3151 to run task
[2023-01-05T11:31:52.158+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UK_Accidents_pipeline', 'load_to_postgres', 'manual__2023-01-05T10:53:41.626541+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/UK_Accidents.py', '--cfg-path', '/tmp/tmphgut3lr0']
[2023-01-05T11:31:52.160+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask load_to_postgres
[2023-01-05T11:31:52.315+0000] {task_command.py:389} INFO - Running <TaskInstance: UK_Accidents_pipeline.load_to_postgres manual__2023-01-05T10:53:41.626541+00:00 [running]> on host 5c8dbd0ba0f2
[2023-01-05T11:31:52.730+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UK_Accidents_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T10:53:41.626541+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T10:53:41.626541+00:00
[2023-01-05T11:31:54.308+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-05T11:31:54.436+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-05T11:33:06.721+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-05T11:33:06.751+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=UK_Accidents_pipeline, task_id=load_to_postgres, execution_date=20230105T105341, start_date=20230105T113152, end_date=20230105T113306
[2023-01-05T11:33:06.964+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-05T11:33:07.008+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
